# @package _global_
model:
  name: libervia-core-2b
  d_model: 2048
  n_layers: 22
  n_heads: 16
  ffn_mult: 2.67
  vocab_size: 32000
  max_sequence_length: 4096
  rope_base: 10000.0
  norm_eps: 1e-6
  use_flash_attention: true
  use_kv_cache: true
